#pragma once

#include <cstdint>

#include "Bus.hh"
#include "CPU.hh"

class SM83 : CPU {
 public:
  SM83(Bus *bus);
  ~SM83();

  void reset() override;
  uint32_t execute() override;
  void executeCBInstruction(uint8_t opcode, uint32_t &cycles);
  uint8_t readMemory(uint32_t &cycles, uint16_t address) override;
  void writeMemory(uint32_t &cycles, uint16_t address, uint8_t value) override;

  uint16_t popStack(uint32_t &cycles);
  uint16_t pushStack(uint32_t &cycles, uint16_t value);

 private:
  uint8_t A, B, C, D, E, H, L;
  uint16_t PC, SP;
  uint8_t F;
  bool IME;  // Interrupt Master Enable flag

  Bus *bus;

  // Instruction set methods
  void ld_bc_d16(uint32_t &cycles);
  void ld_bc_a(uint32_t &cycles);
  void inc_bc(uint32_t &cycles);
  void inc_b();
  void dec_b();
  void ld_b_d8(uint32_t &cycles);
  void rlca();
  void ld_a16_sp(uint32_t &cycles);
  void add_hl_bc(uint32_t &cycles);
  void ld_a_bc(uint32_t &cycles);
  void dec_bc(uint32_t &cycles);
  void inc_c();
  void dec_c();
  void ld_c_d8(uint32_t &cycles);
  void rrca();
  void stop();
  void ld_de_d16(uint32_t &cycles);
  void ld_de_a(uint32_t &cycles);
  void inc_de(uint32_t &cycles);
  void inc_d();
  void dec_d();
  void ld_d_d8(uint32_t &cycles);
  void rla();
  void jr_r8(uint32_t &cycles);
  void add_hl_de(uint32_t &cycles);
  void ld_a_de(uint32_t &cycles);
  void dec_de(uint32_t &cycles);
  void inc_e();
  void dec_e();
  void ld_e_d8(uint32_t &cycles);
  void rra();
  void jr_nz_r8(uint32_t &cycles);
  void ld_hl_d16(uint32_t &cycles);
  void ld_hli_a(uint32_t &cycles);
  void inc_hl(uint32_t &cycles);
  void inc_h();
  void dec_h();
  void ld_h_d8(uint32_t &cycles);
  void daa();
  void jr_z_r8(uint32_t &cycles);
  void add_hl_hl(uint32_t &cycles);
  void ld_a_hli(uint32_t &cycles);
  void dec_hl(uint32_t &cycles);
  void inc_l();
  void dec_l();
  void ld_l_d8(uint32_t &cycles);
  void cpl();
  void jr_nc_r8(uint32_t &cycles);
  void ld_sp_d16(uint32_t &cycles);
  void ld_hl_ptr_minus_a(uint32_t &cycles);
  void inc_sp(uint32_t &cycles);
  void inc_hl_ptr(uint32_t &cycles);
  void dec_hl_ptr(uint32_t &cycles);
  void ld_hl_d8(uint32_t &cycles);
  void scf();
  void jr_c_r8(uint32_t &cycles);
  void add_hl_sp(uint32_t &cycles);
  void ld_a_hld(uint32_t &cycles);
  void dec_sp(uint32_t &cycles);
  void inc_a();
  void dec_a();
  void ld_a_d8(uint32_t &cycles);
  void ccf();
  void ld_b_b();
  void ld_b_c();
  void ld_b_d();
  void ld_b_e();
  void ld_b_h();
  void ld_b_l();
  void ld_b_hl_ptr(uint32_t &cycles);
  void ld_b_a();
  void ld_c_b();
  void ld_c_c();
  void ld_c_d();
  void ld_c_e();
  void ld_c_h();
  void ld_c_l();
  void ld_c_hl_ptr(uint32_t &cycles);
  void ld_c_a();
  void ld_d_b();
  void ld_d_c();
  void ld_d_d();
  void ld_d_e();
  void ld_d_h();
  void ld_d_l();
  void ld_d_hl_ptr(uint32_t &cycles);
  void ld_d_a();
  void ld_e_b();
  void ld_e_c();
  void ld_e_d();
  void ld_e_e();
  void ld_e_h();
  void ld_e_l();
  void ld_e_hl_ptr(uint32_t &cycles);
  void ld_e_a();
  void ld_h_b();
  void ld_h_c();
  void ld_h_d();
  void ld_h_e();
  void ld_h_h();
  void ld_h_l();
  void ld_h_hl_ptr(uint32_t &cycles);
  void ld_h_a();
  void ld_l_b();
  void ld_l_c();
  void ld_l_d();
  void ld_l_e();
  void ld_l_h();
  void ld_l_l();
  void ld_l_hl_ptr(uint32_t &cycles);
  void ld_l_a();
  void ld_hl_b(uint32_t &cycles);
  void ld_hl_c(uint32_t &cycles);
  void ld_hl_d(uint32_t &cycles);
  void ld_hl_e(uint32_t &cycles);
  void ld_hl_h(uint32_t &cycles);
  void ld_hl_l(uint32_t &cycles);
  void halt();
  void ld_hl_a(uint32_t &cycles);
  void ld_a_b();
  void ld_a_c();
  void ld_a_d();
  void ld_a_e();
  void ld_a_h();
  void ld_a_l();
  void ld_a_hl_ptr(uint32_t &cycles);
  void ld_a_a();
  void add_a_b();
  void add_a_c();
  void add_a_d();
  void add_a_e();
  void add_a_h();
  void add_a_l();
  void add_a_hl_ptr(uint32_t &cycles);
  void add_a_a();
  void adc_a_b();
  void adc_a_c();
  void adc_a_d();
  void adc_a_e();
  void adc_a_h();
  void adc_a_l();
  void adc_a_hl_ptr(uint32_t &cycles);
  void adc_a_a();
  void sub_a_b();
  void sub_a_c();
  void sub_a_d();
  void sub_a_e();
  void sub_a_h();
  void sub_a_l();
  void sub_a_hl_ptr(uint32_t &cycles);
  void sub_a_a();
  void sbc_a_b();
  void sbc_a_c();
  void sbc_a_d();
  void sbc_a_e();
  void sbc_a_h();
  void sbc_a_l();
  void sbc_a_hl_ptr(uint32_t &cycles);
  void sbc_a_a();
  void and_a_b();
  void and_a_c();
  void and_a_d();
  void and_a_e();
  void and_a_h();
  void and_a_l();
  void and_a_hl_ptr(uint32_t &cycles);
  void and_a_a();
  void xor_a_b();
  void xor_a_c();
  void xor_a_d();
  void xor_a_e();
  void xor_a_h();
  void xor_a_l();
  void xor_a_hl_ptr(uint32_t &cycles);
  void xor_a_a();
  void or_a_b();
  void or_a_c();
  void or_a_d();
  void or_a_e();
  void or_a_h();
  void or_a_l();
  void or_a_hl_ptr(uint32_t &cycles);
  void or_a_a();
  void cp_a_b();
  void cp_a_c();
  void cp_a_d();
  void cp_a_e();
  void cp_a_h();
  void cp_a_l();
  void cp_a_hl_ptr(uint32_t &cycles);
  void cp_a_a();
  void ret_nz(uint32_t &cycles);
  void pop_bc(uint32_t &cycles);
  void jp_nz_a16(uint32_t &cycles);
  void jp_a16(uint32_t &cycles);
  void call_nz_a16(uint32_t &cycles);
  void push_bc(uint32_t &cycles);
  void add_a_d8(uint32_t &cycles);
  void rst_00(uint32_t &cycles);
  void ret_z(uint32_t &cycles);
  void ret(uint32_t &cycles);
  void jp_z_a16(uint32_t &cycles);
  void prefix_bc(uint32_t &cycles);
  void call_z_a16(uint32_t &cycles);
  void call_a16(uint32_t &cycles);
  void adc_a_d8(uint32_t &cycles);
  void rst_08(uint32_t &cycles);
  void ret_nc(uint32_t &cycles);
  void pop_de(uint32_t &cycles);
  void jp_nc_a16(uint32_t &cycles);
  void call_nc_a16(uint32_t &cycles);
  void push_de(uint32_t &cycles);
  void sub_a_d8(uint32_t &cycles);
  void rst_10(uint32_t &cycles);
  void ret_c(uint32_t &cycles);
  void reti(uint32_t &cycles);
  void jp_c_a16(uint32_t &cycles);
  void call_c_a16(uint32_t &cycles);
  void sbc_a_d8(uint32_t &cycles);
  void rst_18(uint32_t &cycles);
  void ldh_a8_a(uint32_t &cycles);
  void pop_hl(uint32_t &cycles);
  void ldh_c_a(uint32_t &cycles);
  void push_hl(uint32_t &cycles);
  void and_a_d8(uint32_t &cycles);
  void rst_20(uint32_t &cycles);
  void add_sp_r8(uint32_t &cycles);
  void jp_hl(uint32_t &cycles);
  void ld_a16_a(uint32_t &cycles);
  void xor_a_d8(uint32_t &cycles);
  void rst_28(uint32_t &cycles);
  void ldh_a_a8(uint32_t &cycles);
  void pop_af(uint32_t &cycles);
  void ld_a_c(uint32_t &cycles);
  void di();
  void push_af(uint32_t &cycles);
  void or_a_d8(uint32_t &cycles);
  void rst_30(uint32_t &cycles);
  void ld_hl_sp_plus_r8(uint32_t &cycles);
  void ld_sp_hl(uint32_t &cycles);
  void ld_a_a16_ptr(uint32_t &cycles);
  void ei();
  void cp_a_d8(uint32_t &cycles);
  void rst_38(uint32_t &cycles);
};
