/**
 * Interface representing an instance of an emulator, providing methods to load ROMs, control execution, manage input, and access audio and video data.
 * This interface defines the core functionality required to interact with an emulator instance, allowing for loading games, stepping through frames, handling input, and managing audio and video output.
 * @interface EmulatorInstance
 * @method load - Loads a ROM of the specified type into the emulator instance.
 * @method setSampleRate - Sets the audio sample rate for the emulator's audio output.
 * @method reset - Resets the emulator instance to its initial state.
 * @method stepFrame - Advances the emulator by one frame, processing input and updating the state.
 * @method setKey - Sets the pressed state of a specific key in the emulator's input system.
 * @method isHalted - Checks if the emulator is currently halted (paused or stopped).
 * @method width - Returns the width of the emulator's display in pixels.
 * @method height - Returns the height of the emulator's display in pixels.
 * @method framebufferPtr - Returns a pointer to the framebuffer containing pixel data for
 * the current frame.
 */
export interface EmulatorInstance {
  /**
   * Loads a ROM of the specified type into the emulator instance, initializing it for execution.
   * @param type - The type of the ROM to be loaded, corresponding to the system being emulated.
   * @param rom - A Uint8Array containing the binary data of the ROM to be loaded.
   * @returns A boolean indicating whether the ROM was successfully loaded into the emulator instance.
   */
  load(type: string, rom: Uint8Array): boolean;
  /**
   * Sets the audio sample rate for the emulator's audio output, allowing for configuration of the audio playback quality.
   * @param hz - The desired audio sample rate in Hertz (Hz) to be set for the emulator's audio output.
   */
  setSampleRate(hz: number): void;
  /**
   * Resets the emulator instance to its initial state, clearing any loaded ROMs, resetting memory, and returning the emulator to a clean state.
   * This method is typically called to restart the emulation process or to recover from an error state.
   * It ensures that the emulator is ready for a new ROM to be loaded and executed.
   * @returns void
   */
  reset(): void;
  /**
   * Advances the emulator by one frame, processing input and updating the state of the emulated system.
   * This method is called during each iteration of the main loop to simulate the passage of time and to render the next frame of the emulated system.
   * It ensures that the emulator's state is updated based on the current input and that the display and audio output are refreshed accordingly.
   * @returns void
   */
  stepFrame(): void;
  /**
   * Sets the state of a key in the emulator.
   * @param key - The key to set.
   * @param pressed - Whether the key is pressed.
   */
  setKey(key: number, pressed: boolean): void;
  /**
   * Checks if the emulator is currently halted.
   * @returns A boolean indicating whether the emulator is halted.
   */
  isHalted(): boolean;
  /**
   * Returns the width of the emulator's display in pixels.
   * @returns The width of the display in pixels.
   */
  width(): number;
  /**
   * Returns the height of the emulator's display in pixels.
   * @returns The height of the display in pixels.
   */
  height(): number;
  /**
   * Returns a pointer to the framebuffer containing pixel data for the current frame.
   * The framebuffer is a contiguous block of memory that holds the pixel data for the current frame being rendered by the emulator.
   * This pointer can be used to access the pixel data directly for rendering or processing purposes.
   * @returns A number representing the pointer to the framebuffer in memory.
   */
  framebufferPtr(): number;
  /**
   * Returns the number of audio frames available in the emulator's audio output buffer.
   * This method provides information about the amount of audio data that can be processed or played back, allowing for synchronization of audio output with the emulator's execution.
   * @returns A number representing the count of audio frames available in the output buffer.
   */
  audioFrameCount(): number;
  /**
   * Returns a pointer to the audio buffer containing audio data for the current frame.
   * The audio buffer is a contiguous block of memory that holds the audio samples generated by the emulator for the current frame.
   * This pointer can be used to access the audio data directly for playback or processing purposes.
   * @returns A number representing the pointer to the audio buffer in memory.
   */
  audioPtr(): number;
  /**
   * Deletes the emulator instance, releasing any allocated resources and cleaning up memory.
   * This method should be called when the emulator instance is no longer needed to prevent memory leaks and ensure proper resource management.
   * It effectively destroys the emulator instance, making it unusable after this call.
   * @returns void
   */
  delete(): void;
  /**
   * Loads a previously saved state into the emulator instance, restoring its state to that of the saved snapshot.
   * This method allows for saving and loading game progress or emulator configurations, enabling users to return to a specific point in the emulation process.
   * @param state - A string representing the serialized state data to be loaded into the emulator.
   * @returns A boolean indicating whether the state was successfully loaded into the emulator instance.
   */
  loadState(state: string): boolean;
  /**
   * Saves the current state of the emulator instance, serializing its state into a string representation.
   * This method allows for capturing the current state of the emulation process, enabling users to save their progress or configurations for later restoration.
   * @returns A string representing the serialized state data of the emulator instance.
   */
  saveState(): string;
}

/**
 * Interface representing the WebAssembly module for the emulator, providing access to the Emulator class and memory buffers for audio and video data.
 * This interface defines the structure of the WebAssembly module, allowing for the creation of emulator instances and access to the underlying memory used for audio and video processing.
 * @interface EmulatorModule
 * @property {new () => EmulatorInstance} Emulator - The constructor for creating new instances of the emulator.
 * @property {Uint8Array} HEAPU8 - A Uint8Array representing the WebAssembly memory buffer for unsigned 8-bit integer data, used for video and other data.
 * @property {Float32Array} HEAPF32 - A Float32Array representing the WebAssembly memory buffer for 32-bit floating-point data, used for audio and other data.
 */
export interface EmulatorModule {
  /**
   * The constructor for creating new instances of the emulator.
   * This property provides access to the Emulator class, allowing for the instantiation of emulator instances that can load ROMs, process input, and manage audio and video output.
   * @type {new () => EmulatorInstance}
   */
  Emulator: new () => EmulatorInstance;
  /**
   * A Uint8Array representing the WebAssembly memory buffer for unsigned 8-bit integer data.
   * This buffer is used for storing video data, such as pixel information for the emulator's display, as well as other data that requires byte-level access.
   * @type {Uint8Array}
   */
  HEAPU8: Uint8Array;
  /**
   * A Float32Array representing the WebAssembly memory buffer for 32-bit floating-point data.
   * This buffer is used for storing audio data, such as audio samples generated by the emulator, as well as other data that requires floating-point precision.
   * @type {Float32Array}
   */
  HEAPF32: Float32Array;
}

let modulePromise: Promise<EmulatorModule> | null = null;

/**
 * Loads the WebAssembly module for the emulator, returning a promise that resolves to the EmulatorModule interface.
 * If the module has already been loaded, the existing promise is returned; otherwise, a new import is initiated.
 * This function ensures that the WebAssembly module is loaded and ready for use, providing access to the Emulator class and memory buffers for audio and video data.
 * @returns A promise that resolves to the EmulatorModule interface, allowing for the creation of emulator instances and access to memory buffers.
 */
export function loadEmulatorModule(): Promise<EmulatorModule> {
  if (!modulePromise) {
    modulePromise = import('../wasm/emulators.js')
      .then((m) => m.default() as Promise<EmulatorModule>)
      .catch((err) => {
        modulePromise = null;
        throw new Error('Impossible to load the WebAssembly module.', {
          cause: err,
        });
      });
  }

  return modulePromise;
}
