#!/usr/bin/env python3
"""
Generate Markdown wiki pages from Doxygen's XML output.

Overview:
    1. Doxygen produces one XML file per class / struct / file / etc. in
       `build/doxygen/xml`.
    2. This script walks through those files, keeps only classes and structs,
       and writes one Markdown page per element in `build/wiki/api`.
    3. An index page `API.md` listing all generated pages is also created.

Usage:
    python3 generate_wiki.py
    (run from the project root, after Doxygen has been executed)
"""

from __future__ import annotations

import html
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


# Directory containing the XML files generated by Doxygen (input).
XML_DIR = Path("build/doxygen/xml")

# Directory where the Markdown pages are written (output).
OUTPUT_DIR = Path("build/wiki/api")


# ---------------------------------------------------------------------------
# Text cleaning / extraction helpers
# ---------------------------------------------------------------------------

def clean_text(text: str | None) -> str:
    """Clean text coming from Doxygen's XML so it suits Markdown.

    - decodes HTML entities (`&amp;`, `&lt;`, ...);
    - converts a few Doxygen tags to their Markdown equivalents;
    - strips leading and trailing whitespace.

    Returns an empty string if `text` is None or empty.
    """
    if not text:
        return ""

    text = html.unescape(text)

    # Mapping: Doxygen tag -> Markdown syntax.
    # Note: `element_text` relies on `itertext()`, which only returns the raw
    # text (without tags). These replacements therefore only apply if literal
    # tags remain in the text (for example after `html.unescape`).
    replacements = {
        "<computeroutput>": "`",
        "</computeroutput>": "`",
        "<bold>": "**",
        "</bold>": "**",
        "<emphasis>": "*",
        "</emphasis>": "*",
        "<sp/>": " ",
        "<linebreak/>": "\n",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text.strip()


def element_text(element: ET.Element | None) -> str:
    """Return all the text contained in an XML element (including children).

    Returns an empty string if the element does not exist (`find` returned
    None).
    """
    if element is None:
        return ""

    return clean_text("".join(element.itertext()))


def description(element: ET.Element) -> tuple[str, str]:
    """Return the brief and detailed descriptions of an element.

    Returns a `(brief, detailed)` tuple; either value may be empty.
    """
    return (
        element_text(element.find("briefdescription")),
        element_text(element.find("detaileddescription")),
    )


# ---------------------------------------------------------------------------
# Extracting information from a member (function, variable, enum, ...)
# ---------------------------------------------------------------------------

def member_type(member: ET.Element) -> str:
    """Return the member's type (a function's return type, a variable's type,
    a typedef's underlying type...)."""
    return element_text(member.find("type"))


def member_arguments(member: ET.Element) -> str:
    """Rebuild a function's argument list from its `<param>` tags
    (type + name), e.g. `"int a, const char* b"`.

    Used as a fallback when `<argsstring>` is missing.
    """
    arguments = []

    for param in member.findall("param"):
        param_type = element_text(param.find("type"))
        param_name = element_text(param.find("declname"))

        # Empty parts are skipped (e.g. an unnamed parameter).
        argument = " ".join(
            part
            for part in (param_type, param_name)
            if part
        )

        if argument:
            arguments.append(argument)

    return ", ".join(arguments)


def member_name(member: ET.Element) -> str:
    """Return the member's name.

    Looks at the `<name>` tag first, then falls back on the `name` attribute.
    Returns an empty string if no name is found.
    """
    name = element_text(member.find("name"))

    if name:
        return name

    name = member.get("name")

    if name:
        return name

    return ""


def member_signature(member: ET.Element) -> str:
    """Build a function's displayable signature, e.g. `foo(int a) const`.

    Strategy:
        1. get the name (falling back on the `<definition>` tag);
        2. use `<argsstring>` if present (it already includes the
           parentheses and qualifiers such as `const`);
        3. otherwise rebuild the arguments with `member_arguments`.

    Returns an empty string if no name could be determined.
    """
    name = member_name(member)

    # Fallback: extract the name from the full definition
    # (e.g. "void Ns::Class::method" -> "method").
    if not name:
        definition = element_text(member.find("definition"))

        if definition:
            name = definition.split("::")[-1]

    if not name:
        return ""

    args = element_text(member.find("argsstring"))

    if args:
        # Remove the `override` and `final` qualifiers: they are not part of
        # the argument list and clutter the display.
        args = args.strip()

        args = args.replace(" override", "")
        args = args.replace(" final", "")

        return f"{name}{args}"

    return f"{name}({member_arguments(member)})"


def parameter_descriptions(member: ET.Element) -> list[tuple[str, str]]:
    """Extract the documentation of the parameters (`@param` commands).

    Returns a list of `(parameter_name, description)` tuples.
    """
    result = []

    detailed = member.find("detaileddescription")

    if detailed is None:
        return result

    # Each `@param` is represented by a <parameteritem> inside a
    # <parameterlist kind="param">.
    for parameter in detailed.findall(".//parameterlist[@kind='param']/parameteritem"):
        name = element_text(parameter.find("parameternamelist/parametername"))
        desc = element_text(
            parameter.find("parameterdescription")
        )

        # Entries without a name are ignored.
        if name:
            result.append((name, desc))

    return result


def return_description(member: ET.Element) -> str:
    """Extract the documentation of the return value (`@return` command).

    Returns an empty string if it is not documented.
    """
    detailed = member.find("detaileddescription")

    if detailed is None:
        return ""

    # Only the first `@return` section found is kept.
    for parameter_list in detailed.findall(
        ".//simplesect[@kind='return']"
    ):
        return element_text(parameter_list)

    return ""


def source_location(member: ET.Element) -> str:
    """Return the path of the source file where the member is declared."""
    location = member.find("location")

    if location is None:
        return ""

    return location.get("file", "")


# ---------------------------------------------------------------------------
# Generating a Markdown page for a class / struct
# ---------------------------------------------------------------------------

def write_compound(compound: ET.Element) -> Path | None:
    """Generate the Markdown page of a `<compounddef>` (class or struct).

    Other kinds of compounds (files, namespaces, groups, ...) are ignored.

    Returns the path of the written file, or None if nothing was generated.
    """
    kind = compound.get("kind")

    # Only classes and structs are documented.
    if kind not in {"class", "struct"}:
        return None

    name = element_text(compound.find("compoundname"))

    if not name:
        return None

    # `::` is replaced by `_` in the file name to avoid problematic characters
    # (e.g. "ns::Class" -> "ns_Class.md").
    filename = name.replace("::", "_") + ".md"
    output = OUTPUT_DIR / filename

    brief, detailed = description(compound)

    # `lines` accumulates every line of the page; they are joined with
    # newlines at the end of the function.
    lines = [
        f"# `{name}`",
        "",
        f"**Type:** {kind}",
        "",
    ]

    if brief:
        lines += [brief, ""]

    if detailed:
        lines += [detailed, ""]

    # ----- Inheritance -----------------------------------------------------
    bases = []

    for base in compound.findall("basecompoundref"):
        base_name = element_text(base)

        if base_name:
            bases.append(base_name)

    if bases:
        lines += [
            "## Inheritance",
            "",
        ]

        for base in bases:
            lines.append(f"- `{base}`")

        lines.append("")

    # ----- Sorting members by category -------------------------------------
    functions = []
    variables = []
    enums = []
    typedefs = []

    # Members are spread across several <sectiondef> (public, private,
    # static, ...). Here they are simply grouped by nature.
    for section in compound.findall("sectiondef"):
        for member in section.findall("memberdef"):
            member_kind = member.get("kind")

            if member_kind == "function":
                functions.append(member)

            elif member_kind == "variable":
                variables.append(member)

            elif member_kind == "enum":
                enums.append(member)

            elif member_kind == "typedef":
                typedefs.append(member)

    # ----- Functions -------------------------------------------------------
    if functions:
        lines += [
            "## Functions",
            "",
        ]

        for function in functions:
            signature = member_signature(function)

            # Skip the function if no usable signature could be built.
            if not signature:
                continue

            return_type = member_type(function)
            brief, detailed = description(function)

            lines.append(f"### `{signature}`")
            lines.append("")

            if return_type:
                lines.append(f"**Return type:** `{return_type}`")
                lines.append("")

            if brief:
                lines.append(brief)
                lines.append("")

            if detailed:
                lines.append(detailed)
                lines.append("")

            # Table of documented parameters.
            parameters = parameter_descriptions(function)

            if parameters:
                lines += [
                    "#### Parameters",
                    "",
                    "| Name | Description |",
                    "|---|---|",
                ]

                for name, parameter_description in parameters:
                    lines.append(
                        f"| `{name}` | {parameter_description} |"
                    )

                lines.append("")

            # Documented return value.
            returns = return_description(function)

            if returns:
                lines += [
                    "#### Returns",
                    "",
                    returns,
                    "",
                ]

            # Source file of the declaration.
            source = source_location(function)

            if source:
                lines += [
                    f"**Source:** `{source}`",
                    "",
                ]

    # ----- Member variables ------------------------------------------------
    if variables:
        lines += [
            "## Variables",
            "",
        ]

        for variable in variables:
            name = member_name(variable)

            if not name:
                continue

            variable_type = member_type(variable)
            brief, detailed = description(variable)

            # Heading: "type name" if the type is known, otherwise just the name.
            if variable_type:
                lines += [
                    f"### `{variable_type} {name}`",
                    "",
                ]
            else:
                lines += [
                    f"### `{name}`",
                    "",
                ]

            if brief:
                lines += [brief, ""]

            if detailed:
                lines += [detailed, ""]

    # ----- Enumerations ----------------------------------------------------
    if enums:
        lines += [
            "## Enumerations",
            "",
        ]

        for enum in enums:
            # An unnamed enumeration is displayed as "anonymous".
            name = member_name(enum) or "anonymous"
            brief, detailed = description(enum)

            lines += [
                f"### `{name}`",
                "",
            ]

            if brief:
                lines += [brief, ""]

            if detailed:
                lines += [detailed, ""]

            # List of the enumeration's values, with their description
            # (brief one first, otherwise the detailed one).
            for value in enum.findall("enumvalue"):
                value_name = element_text(value.find("name")) or value.get("name", "")
                val_brief, val_detailed = description(value)
                val_desc = val_brief or val_detailed

                if value_name:
                    if val_desc:
                        lines.append(f"- `{value_name}`: {val_desc}")
                    else:
                        lines.append(f"- `{value_name}`")

            lines.append("")

    # ----- Type definitions (typedef / using) ------------------------------
    if typedefs:
        lines += [
            "## Type definitions",
            "",
        ]

        for typedef in typedefs:
            name = member_name(typedef) or typedef.get("name", "unknown")
            typedef_type = member_type(typedef)
            brief, detailed = description(typedef)

            # Heading: "type name" if the type is known, otherwise just the name.
            if typedef_type:
                lines += [
                    f"### `{typedef_type} {name}`",
                    "",
                ]
            else:
                lines += [
                    f"### `{name}`",
                    "",
                ]

            if brief:
                lines += [brief, ""]

            if detailed:
                lines += [detailed, ""]

    # ----- Footer ----------------------------------------------------------
    lines += [
        "---",
        "",
        "*Automatically generated from Doxygen XML.*",
        "",
    ]

    output.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    return output


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Walk through Doxygen's XML files, then generate the pages and the index."""

    # Preliminary check: Doxygen must have been run beforehand.
    if not XML_DIR.exists():
        print(
            f"ERROR: Doxygen XML directory does not exist: {XML_DIR}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Create the output directory if it does not exist.
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Remove previously generated pages so no stale page is kept
    # (classes deleted or renamed since the last run).
    for file in OUTPUT_DIR.glob("*.md"):
        file.unlink()

    # Sorted to get deterministic processing (and console output).
    xml_files = sorted(XML_DIR.glob("*.xml"))

    print(f"Found {len(xml_files)} XML files.")

    generated = []

    for xml_file in xml_files:
        # An invalid XML file must not abort the whole generation:
        # print a warning and move on to the next one.
        try:
            tree = ET.parse(xml_file)
        except ET.ParseError as error:
            print(
                f"WARNING: Could not parse {xml_file}: {error}",
                file=sys.stderr,
            )
            continue

        root = tree.getroot()

        # A Doxygen XML file normally contains a single <compounddef>
        # ("index.xml" contains none and is therefore skipped).
        compounds = root.findall("compounddef")

        for compound in compounds:
            output = write_compound(compound)

            # `write_compound` returns None for ignored compounds.
            if output is not None:
                generated.append(output)

    # ----- API index page --------------------------------------------------
    index = OUTPUT_DIR / "API.md"

    lines = [
        "# API Reference",
        "",
        "Automatically generated from the C++ source code using Doxygen.",
        "",
    ]

    if generated:
        lines += [
            "## Classes and structures",
            "",
        ]

        # One relative Markdown link per generated page, sorted alphabetically.
        for page in sorted(generated):
            name = page.stem

            lines.append(
                f"- [`{name}`]({page.name})"
            )

        lines.append("")

    else:
        lines += [
            "No classes or structures were found.",
            "",
        ]

    index.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    # Summary printed to the console.
    print(f"Generated {len(generated)} API pages.")

    for page in sorted(generated):
        print(f"  {page}")


# Run `main()` only when the file is executed directly
# (not when it is imported as a module).
if __name__ == "__main__":
    main()
